version: '3.8'

services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5001:5001"  # Expor a porta 5001 para a aplicação Flask
    volumes:
      - ./app:/chatbot/app  # Vincular o código local para desenvolvimento
    networks:
      - app-network
    depends_on:
      - ollama-server
    environment:
      - OLLAMA_URL=http://ollama-server:11434  # Defina o URL do Ollama no container
    command: gunicorn app:app --bind 0.0.0.0:5001  # Configuração para rodar a aplicação com Gunicorn

  ollama-server:
    image: ollama/ollama:latest  # Supondo que o Ollama tenha uma imagem oficial no Docker Hub
    container_name: ollama-server
    ports:
      - "11435:11434"  # A porta 11434 é mapeada para acessar o serviço
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8888:80"  # Expor a porta 80 para o Nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Arquivo de configuração do Nginx
    networks:
      - app-network
    depends_on:
      - flask-app

networks:
  app-network:
    driver: bridge
